### PR TITLE
Set up sbt build

### PR DESCRIPTION
**Pull request by mrerrormessage**
(perhaps using https://github.com/NetLogo/NetLogo-Extension-Plugin ?)

Will be needed for bundling.

### CODE REVIEW

**Comment by mrerrormessage** [comment]
This is ready for testing. I'm happy to test it, but I don't have an arduino to test with. [This version of NetLogo](http://ccl.northwestern.edu/devel/NetLogo%205.3-PREVIEW.dmg) can be used to test. If you need a windows or linux build, let me know and I'll get it for you.

**Comment by nicolaspayette** [comment]
> This is ready for testing.

Thanks!

> I'm happy to test it, but I don't have an arduino to test with.

Neither do I! But maybe @cbradyatinquire could give it a go... :-)

**Pull request closed without merging**
